services:
  postgres-a:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "15432:5432"
    tmpfs:
      - /var/lib/postgresql/data:size=256m
    volumes:
      - ./docker/postgres/init-a:/docker-entrypoint-initdb.d:ro

  postgres-b:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "25432:5432"
    tmpfs:
      - /var/lib/postgresql/data:size=256m
    volumes:
      - ./docker/postgres/init-b:/docker-entrypoint-initdb.d:ro
